version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    ports:
      # The HTTP port
      - "85:85"
      # The Web UI (enabled by --api.insecure=true)
      - "8085:8085"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  profile:
    build:
      context: ./profile
      dockerfile: Dockerfile
    # working_dir value has to be the same of mapped volume
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.profile.rule=Host(`profile.example.com`)"
      - "traefik.http.services.profile.loadbalancer.server.port=8080"
    ports:
      - "8080:8080"
    volumes:
      - ./profile:/app  #set the volume of where main.go is placed which is ./profile in this case
    # command: ["gin", "run", "main.go"]  # Use Gin for live reloading

  traefik:
    image: traefik:v2.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:81"
    ports:
      - "81:81"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mounting nginx.conf
  #   ports:
  #     - "80:80"
  #     - "443:443"